In [23]:
# Importing the library
import tensorflow as tf
 
# Initializing the input
x = tf.constant([[2, 3, 6], [4, 8, 15]], dtype=tf.float32)
y = tf.constant([[6, 8, 10], [9, 9, 1]], dtype=tf.float32)
 
# Printing the input
print('x:', x)
 
# Calculating result
# res = tf.expand_dims(x, 1)
# res2 = tf.expand_dims(y, 1)

x: tf.Tensor(
[[ 2.  3.  6.]
 [ 4.  8. 15.]], shape=(2, 3), dtype=float32)


In [24]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  3.,  6.],
       [ 4.,  8., 15.]], dtype=float32)>

axis จะคล้าย reduce_sum เมื่อกำหนด axis ที่แถวนั้น แถวนั้นจะหายไป

In [36]:
dist = tf.norm(x - y)
print(dist)
dist = tf.norm(x - y, axis=0)
print(dist)
dist = tf.norm(x - y, axis=1)
print(dist)

tf.Tensor(16.703293, shape=(), dtype=float32)
tf.Tensor([ 6.403124   5.0990195 14.56022  ], shape=(3,), dtype=float32)
tf.Tensor([ 7.5498343 14.899664 ], shape=(2,), dtype=float32)


In [37]:
dist = tf.norm(x - y, axis=-1)
print(dist)
dist = tf.norm(x - y, axis=-2)
print(dist)

tf.Tensor([ 7.5498343 14.899664 ], shape=(2,), dtype=float32)
tf.Tensor([ 6.403124   5.0990195 14.56022  ], shape=(3,), dtype=float32)
