In [76]:
import tensorflow as tf

In [77]:
# x = tf.constant([num for num in range(1,28) ], shape=[3,3,3], dtype=tf.float32)



encoder = tf.constant([
    [1, 2],
    [4, 5],
    [6, 7],
    [14, 1],
    [8, 5],
    [567, 747],
    [1, 2],
    [4, 5],
    [6, 7],
    [14, 1],
    [8, 5],
    [567, 747]
    ], dtype=tf.float32)


codebook = tf.constant([
    [1, 2],
    [4, 5],
    [6, 7],
    [14, 1],
    [8, 5],
    [567, 747]
    ], dtype=tf.float32)


In [78]:
print(encoder)
print(codebook)

tf.Tensor(
[[  1.   2.]
 [  4.   5.]
 [  6.   7.]
 [ 14.   1.]
 [  8.   5.]
 [567. 747.]
 [  1.   2.]
 [  4.   5.]
 [  6.   7.]
 [ 14.   1.]
 [  8.   5.]
 [567. 747.]], shape=(12, 2), dtype=float32)
tf.Tensor(
[[  1.   2.]
 [  4.   5.]
 [  6.   7.]
 [ 14.   1.]
 [  8.   5.]
 [567. 747.]], shape=(6, 2), dtype=float32)


In [83]:
# result = tf.matmul(encoder, codebook)
# result = tf.matmul(encoder, codebook,transpose_a = True)
result = tf.matmul(encoder, codebook,transpose_b = True)

In [80]:
print(result)

tf.Tensor(
[[5.00000e+00 1.40000e+01 2.00000e+01 1.60000e+01 1.80000e+01 2.06100e+03]
 [1.40000e+01 4.10000e+01 5.90000e+01 6.10000e+01 5.70000e+01 6.00300e+03]
 [2.00000e+01 5.90000e+01 8.50000e+01 9.10000e+01 8.30000e+01 8.63100e+03]
 [1.60000e+01 6.10000e+01 9.10000e+01 1.97000e+02 1.17000e+02 8.68500e+03]
 [1.80000e+01 5.70000e+01 8.30000e+01 1.17000e+02 8.90000e+01 8.27100e+03]
 [2.06100e+03 6.00300e+03 8.63100e+03 8.68500e+03 8.27100e+03 8.79498e+05]
 [5.00000e+00 1.40000e+01 2.00000e+01 1.60000e+01 1.80000e+01 2.06100e+03]
 [1.40000e+01 4.10000e+01 5.90000e+01 6.10000e+01 5.70000e+01 6.00300e+03]
 [2.00000e+01 5.90000e+01 8.50000e+01 9.10000e+01 8.30000e+01 8.63100e+03]
 [1.60000e+01 6.10000e+01 9.10000e+01 1.97000e+02 1.17000e+02 8.68500e+03]
 [1.80000e+01 5.70000e+01 8.30000e+01 1.17000e+02 8.90000e+01 8.27100e+03]
 [2.06100e+03 6.00300e+03 8.63100e+03 8.68500e+03 8.27100e+03 8.79498e+05]], shape=(12, 6), dtype=float32)
