In [ ]:
import tensorflow as tf


In [7]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
e = tf.constant([10, 11])
tf.stack([x, y, z, e])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [10, 11]])>

-1 คือเอาจำนวนมาต่อกันเป็น col
และเอา col เดิมมาทำเป็น row

In [8]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
e = tf.constant([10, 11])
tf.stack([x, y, z, e], axis=-1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])>